# Generated by Django 2.2 on 2021-01-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='admin',
            new_name='hr_admin',
        ),
    ]
