# Generated by Django 2.2 on 2021-01-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_faqs_holidays_policies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
