# Generated by Django 2.2 on 2021-01-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leavemodel_is_approve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemodel',
            options={'ordering': ('-id',)},
        ),
    ]
